DROP POLICY IF EXISTS "Allow public delete from course-gifs" ON storage.objects;
DROP POLICY IF EXISTS "Allow public delete from course-videos" ON storage.objects;
DROP POLICY IF EXISTS "Allow public read access to course-gifs" ON storage.objects;
DROP POLICY IF EXISTS "Allow public read access to course-videos" ON storage.objects;
DROP POLICY IF EXISTS "Allow public update to course-gifs" ON storage.objects;
DROP POLICY IF EXISTS "Allow public update to course-videos" ON storage.objects;
DROP POLICY IF EXISTS "Allow public upload to course-gifs" ON storage.objects;
DROP POLICY IF EXISTS "Allow public upload to course-videos" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can delete from course-files" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can read course files" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can read from course-files" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can update course-files" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload course files" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload to course-files" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload videos" ON storage.objects;
DROP POLICY IF EXISTS "Public read access to video-uploads" ON storage.objects;
DROP POLICY IF EXISTS "Service role can delete from course-gifs" ON storage.objects;
DROP POLICY IF EXISTS "Service role can delete from course-videos" ON storage.objects;
DROP POLICY IF EXISTS "Service role can manage course files" ON storage.objects;
DROP POLICY IF EXISTS "Service role can manage video-uploads" ON storage.objects;
DROP POLICY IF EXISTS "Service role can update course-gifs" ON storage.objects;
DROP POLICY IF EXISTS "Service role can update course-videos" ON storage.objects;
DROP POLICY IF EXISTS "Service role can upload to course-gifs" ON storage.objects;
DROP POLICY IF EXISTS "Service role can upload to course-videos" ON storage.objects;
